---

title: V1
description: Don't push the button!
author: openescape
specVersion: 1
durationSeconds: 60
actions:
  hint-available:
    type: HINT_AVAILABLE
    config: resources/hints/hint1.png
  hint-critical:
    type: HINT_CRITICAL
    config:
  game-won:
    type: GAME_VICTORY
    config:
  game-lost:
    type: GAME_LOSS
    config:
conditions:
  button-pressed:
    type: BUTTON_PRESSED
    value: button-1
  30-seconds-remaining-condition:
    type: SECONDS_REMAINING
    value: 30
  15-seconds-remaining-condition:
    type: SECONDS_REMAINING
    value: 15
  0-seconds-remaining-condition:
    type: SECONDS_REMAINING
    value: 0
checkpoints:
triggers:
  - enableConditionId:
    disableConditionId: button-pressed
    triggerConditionId: 30-seconds-remaining-condition
    actionIds: [hint-available]
  - enableConditionId:
    disableConditionId: button-pressed
    triggerConditionId: 15-seconds-remaining-condition
    actionIds: [hint-critical]
  - enableConditionId:
    disableConditionId:
    triggerConditionId: button-pressed
    actionIds: [game-won]
  - enableConditionId:
    disableConditionId:
    triggerConditionId: 0-seconds-remaining-condition
    actionIds: [game-lost]
components:
  button-1:
    type: BUTTON
    inputPin: d12

...