---

title: Simple Game
description: A simple game
author: openescape
specVersion: 1
durationSeconds: 60
hints:
actions:
  turn-light-on:
    type: TURN_LIGHT_ON
    config:
conditions:
  53-seconds-passed-condition:
    type: SECONDS_REMAINING
    value: 53
  55-seconds-passed-condition:
    type: SECONDS_REMAINING
    value: 55
  40-seconds-passed-condition:
    type: SECONDS_REMAINING
    value: 40
checkpoints:
triggers:
  - enableConditionId: 55-seconds-passed-condition
    disableConditionId: 40-seconds-passed-condition
    triggerConditionId: 53-seconds-passed-condition
    actionIds: [turn-light-on]
components:

...